Rails.application.routes.draw do
  root 'static#index'

  get 'about'   => 'static#about'
  get 'contact' => 'static#contact'
  get 'now'     => 'static#now'
  get 'talks'   => 'static#talks'
  get 'me'      => 'static#me'

  get 'blog'    => 'blog#index'
  get 'blog/3'  => 'blog#post_three'
  get 'blog/4'  => 'blog#post_four'
  get 'blog/5'  => 'blog#post_five'
  get 'blog/6'  => 'blog#post_six'
  get 'blog/7'  => 'blog#post_seven'
  get 'blog/8'  => 'blog#post_eight'
  get 'blog/9'  => 'blog#post_nine'
  get 'blog/10' => 'blog#post_ten'
  get 'blog/11' => 'blog#post_eleven'
  get 'blog/12' => 'blog#post_twelve'

  get 'blog/3/blog-buddies'                               => 'blog#post_three'
  get 'blog/4/getting-and-setting-cookies-in-javascript'  => 'blog#post_four'
  get 'blog/5/rubys-enumerable-module-and-you'            => 'blog#post_five'
  get 'blog/6/adventures-of-a-one-woman-development-team' => 'blog#post_six'
  get 'blog/7/the-ins-and-outs-of-put-and-patch'          => 'blog#post_seven'
  get 'blog/8/upgrading-rails-doesnt-have-to-be-painful'  => 'blog#post_eight'
  get 'blog/9/apprenticeship-patterns-lessons-learned'    => 'blog#post_nine'
  get 'blog/10/files-created-by-rails-generators'         => 'blog#post_ten'
  get 'blog/11/your-own-personal-gitignore'               => 'blog#post_eleven'
  get 'blog/12/how-to-become-a-senior-software-engineer-in-2-years-or-less' => 'blog#post_twelve'
end
